package com.boredgames.server.events;

public enum BoredEventType {
    EVENT_TEST,
    EVENT_INFO,
    EVENT_WARNING,
    EVENT_ERROR,
    EVENT_GET_GAME_STATUS,
    EVENT_GAME_STATUS,
    EVENT_GET_GAME_STATE,
    EVENT_GAME_STATE,
    EVENT_CONNECT_WITH_PLAYER_NAME,
    EVENT_CONNECTION_SUCCESS,
    EVENT_START_THE_GAME,
    EVENT_GAME_STARTED
}
