package com.boredgames.server.events;

public enum BoredEventType {
    EVENT_INFO,
    EVENT_WARNING,
    EVENT_ERROR,
    EVENT_GET_GAME_STATE,
    EVENT_GAME_STATE,
    EVENT_CONNECT_WITH_PLAYER_NAME,
    EVENT_CONNECTION_SUCCESS,
    EVENT_START_THE_GAME,
    EVENT_GAME_STARTED,
    EVENT_STOP_THE_GAME,
    EVENT_GAME_STOPPED,
    EVENT_PLAY_CARD,
    EVENT_ERROR_MADE,
    EVENT_GAME_LOST,
    EVENT_NEW_ROUND
}